### ISSUE TITLE
ENH: add end of life info

### ISSUE THREAD

**Issue by mattip** [mayeut/pep600_compliance#13]
This is a great reference for library maintainers looking to distribute PEP 600 tagged wheels. It might be helpful to provide end of life info as well, or at least a “defunct” category to know what no longer needs supporting

**Comment by mayeut** [comment]
Agreed, however, I don't really know how to present this information (and unfortunately, its retrieval can't be automated, 77 distros to check manually as of today). Any suggestion ?

**Comment by mattip** [comment]
Maybe it would be indicative enough just to mark the big 4 (CentOS, RHEL, debian, Ubuntu) and put in parenthesis after Ubuntu 14.04, 12.04, debian 7, 8 EOL (and in Nov add CentOS + RHEL 5,6).

**Comment by mayeut** [comment]
@mattip,
I created 3 branches with that information.
In all cases, color coding is the same:
black: has reached EOL for more than 1 year
red: has reached EOL less than 1 year ago
yellow: will reach EOL in less than 1 year
green: will reach EOL in more than 1 year
purple: rolling release
lightgray: EOL date unknown

EOL fully displayed: https://github.com/mayeut/pep600_compliance/blob/color-coded-eol/README.rst
EOL fully displayed v2: https://github.com/mayeut/pep600_compliance/blob/color-coded-eol2/README.rst
EOL only color encoded: https://github.com/mayeut/pep600_compliance/tree/color-coded-version-eol/README.rst

Neither of those fully satisfy me...
If you have some feedback on either, I'd be happy to read it.

The other thing I'm not happy with is that even the basic README has too much information. I might want to try to get a summarized version as README (i.e merge all architectures in one table, kind of intersection for eligible image and union for distro compatibility), having EOL only color coded. Then, add another file similar to the README in https://github.com/mayeut/pep600_compliance/blob/color-coded-eol/README.rst for those who want to get all the information.
Any thoughts ?

**Comment by mattip** [comment]
Wow, that is impressive. The color coded badges are nice, but perhaps text would be simpler "debian7: EOL 1.2.2021" I like the layout in terms of two tables: building and testing. I think this has value not only for manylinux, but in general conveys important data that is hard to find.

I did see this site https://endoflife.software/operating-systems/ that separates systems with a page for each.

**Comment by mayeut** [comment]
EOL infos added in multiple places. It might be a good thing to update the layout at some point but the information is there.
