### ISSUE TITLE
Add debian bookworm

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/pep600_compliance#302]
Alias Debian 12. Released about a month ago, it [uses](https://distrowatch.com/table.php?distribution=debian) glibc 2.36. Worth noting that according to that link, "Debian (experimental)" is already on 2.37.

Speaking of new versions, Mageia 9 [seems](https://blog.mageia.org/en/2023/05/24/the-release-of-beta2-brings-mageia-9-stable-closer-to-reality/) to be in version hardfreeze and also uses glibc 2.36

**Comment by mayeut** [comment]
Thanks for the heads-up.
I'll let the automated update catch up for Debian experimental.
Mageia 9 is not yet available, I'll recheck in a a couple weeks.
