### ISSUE TITLE
Maybe add RHEL EOL dates?

### ISSUE THREAD

**Issue by mattip** [mayeut/pep600_compliance#306]
conda-forge builds using CentOS, but will continue supporting it according to the EOL schedule of RHEL. So for instance, they have announced [support for CentOS6](https://conda-forge.org/docs/user/announcements.html#end-of-life-for-centos-6) until  June 30, 2024, and will probably support CentOS 7 until June 30, 2028. (see the discussion in the PR around the announcement conda-forge/conda-forge.github.io#1980. THis might have implications for projects, since conda-forge might still be using older glibc until 2028

**Comment by h-vetinari** [comment]
> and will probably support CentOS 7 until June 30, 2028

That's completely speculative. RHEL's ELTS has no bearing on our infrastructure, and while we've postponed dropping CentOS 6 many times (for various reasons), there's no guarantee at all that we'll do the same with the ELTS for CentOS 7.

The one factor that might reasonably extend the lifecycle is if there are many users (or key consumers) stuck on some old distro, but I expect that we'll start feeling the pressure of individual projects requiring newer glibc's (there are already some key projects that require >=2.24), and eventually the maintenance effort falls out of whack with how many users are still served by that.

Looking at the [glibc distribution](https://mayeut.github.io/manylinux-timeline/) (for non-EOL Pythons, which is all what conda-forge builds[^1]), I expect glibc<2.28 (== RHEL 8) to fall into the low single digits of DL % over the next 2-3 years.

[^1]: would be good to get conda-based data, not proxied by pip downloads

**Comment by h-vetinari** [comment]
FWIW, I support having the RHEL dates explicitly in the distro overview (even though they're implicitly there through rhubi at least).

**Comment by mayeut** [comment]
The best I could do given the code base was to add ELTS to `rhubi`. `rhubi` does not get ELTS support if I'm not mistaken and has the same regular EOL as `rhel`. Please refer to `rhubi` for `rhel` EOL.
