### ISSUE TITLE
Add `2_36` and `2_39` to "acceptable distros"

### ISSUE THREAD

**Issue by h-vetinari** [mayeut/pep600_compliance#362]
Based on Debian Bookworm (glibc 2.36) and Ubuntu 24.04 (glibc 2.39). The latter also needs to be added to the distro compatibility table.

PS. I know that 24.04 isn't released yet, but the glibc version is fixed already.

**Comment by mayeut** [comment]
This will happen automatically if need be.
Debian bookworm probably has newer symbols than other distros with glibc 2.36+ and thus is not reported as an "acceptable" distro.

**Comment by h-vetinari** [comment]
> Debian bookworm probably has newer symbols than other distros with glibc 2.36+ and thus is not reported as an "acceptable" distro.

Is there any way to substantiate that hypothesis?
